### ISSUE TITLE
Discovery failed with error argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by BoomerangThree** [dbarentine/udi-totalconnect-poly#9]
Hi again @dbarentine 

Next step and issue with udi-totalconnect-poly that maybe you can assist with.  

The Totcal Connect Controller gets added to ISY, but when Polisy / udi=totalconnect-poly is discovering nodes, ISY doesn't get updated because, I believe, of the error below.  My alarm panel looks like it has a zone labeled 'NoneType'.  The panel itself is pretty old, been working fine for many years, so perhaps you can account for this in your next update of code?

===========================================================
2020-03-04 19:50:58,898 [NodeServer] [DEBUG] Found device GSMX4G in location Home
2020-03-04 19:50:58,899 [NodeServer] [DEBUG] Adding security device panel_326989 with name GSMX4G for location Home
2020-03-04 19:50:58,900 [NodeServer] [INFO ] Adding node Home - GSMX4G(panel_326989)
2020-03-04 19:50:59,015 [Controller] [DEBUG] Query zone panel_326989
2020-03-04 19:50:59,158 [NodeServer] [DEBUG] Getting zones for panel panel_326989
2020-03-04 19:50:59,159 [NodeServer] [DEBUG] Adding zone z_326989_1 with name Home - GARAGE DOOR for location Home
2020-03-04 19:50:59,163 [NodeServer] [INFO ] Adding node Home - GARAGE DOOR(z_326989_1)
2020-03-04 19:50:59,167 [NodeServer] [DEBUG] Adding zone z_326989_2 with name Home - FRONT DOOR for location Home
2020-03-04 19:50:59,169 [NodeServer] [INFO ] Adding node Home - FRONT DOOR(z_326989_2)
2020-03-04 19:50:59,172 [NodeServer] [DEBUG] Adding zone z_326989_3 with name Home - KITCHEN DOOR for location Home
2020-03-04 19:50:59,175 [NodeServer] [INFO ] Adding node Home - KITCHEN DOOR(z_326989_3)
2020-03-04 19:50:59,178 [NodeServer] [DEBUG] Adding zone z_326989_4 with name Home - BASEMENT DOOR for location Home
2020-03-04 19:50:59,179 [NodeServer] [INFO ] Adding node Home - BASEMENT DOOR(z_326989_4)
2020-03-04 19:50:59,183 [NodeServer] [DEBUG] Adding zone z_326989_5 with name Home - MAIN MOTION for location Home
2020-03-04 19:50:59,185 [NodeServer] [INFO ] Adding node Home - MAIN MOTION(z_326989_5)
2020-03-04 19:50:59,187 [NodeServer] [DEBUG] Adding zone z_326989_6 with name Home - BASEMENT MOTION for location Home
2020-03-04 19:50:59,189 [NodeServer] [INFO ] Adding node Home - BASEMENT MOTION(z_326989_6)
2020-03-04 19:50:59,193 [NodeServer] [DEBUG] Skipping zone 7 with name UPSTAIRS SMOKE
2020-03-04 19:50:59,195 [NodeServer] [DEBUG] Adding zone z_326989_8 with name Home -  for location Home
2020-03-04 19:50:59,197 [NodeServer] [INFO ] Adding node Home - (z_326989_8)
2020-03-04 19:50:59,200 [NodeServer] [DEBUG] Skipping zone 9 with name BASEMENT SMOKE
2020-03-04 19:50:59,201 [NodeServer] [DEBUG] Skipping zone 10 with name BASEMENT GAS
2020-03-04 19:50:59,202 [NodeServer] [DEBUG] Skipping zone 11 with name UPSTAIRS GAS
2020-03-04 19:50:59,202 [NodeServer] [DEBUG] Adding zone z_326989_12 with name Home - POLICE PANIC for location Home
2020-03-04 19:50:59,204 [NodeServer] [INFO ] Adding node Home - POLICE PANIC(z_326989_12)
2020-03-04 19:50:59,208 [NodeServer] [DEBUG] Found device Automation in location Home
2020-03-04 19:50:59,209 [NodeServer] [INFO ] Sending addnotice to Polyglot: {'key': 'discovery_failed', 'value': 'Discovery failed please check logs for a more detailed error.'}
2020-03-04 19:50:59,212 [NodeServer] [ERROR] Discovery failed with error argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "./totalconnect-poly.py", line 132, in discover
    if device['DeviceName'] in VALID_DEVICES or 'PanelType' in device['DeviceFlags']:
TypeError: argument of type 'NoneType' is not iterable
2020-03-04 19:50:59,227 [NodeServer] [ERROR] Exception in thread NodeServer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./totalconnect-poly.py", line 76, in start
    schedule.every(int(self.refresh_auth_interval)).minute.do(self.authenticate)
  File "/var/polyglot/.local/lib/python3.7/site-packages/schedule/__init__.py", line 258, in minute
    raise IntervalError('Use minutes instead of minute')
schedule.IntervalError: Use minutes instead of minute
2020-03-04 19:50:59,595 [Controller] [INFO ] Updating All Drivers to ISY for Home - GSMX4G(panel_326989)
2020-03-04 19:50:59,601 [Controller] [DEBUG] Query zone z_326989_1
2020-03-04 19:51:00,381 [Controller] [INFO ] Updating All Drivers to ISY for Home - GARAGE DOOR(z_326989_1)
2020-03-04 19:51:00,386 [Controller] [DEBUG] Query zone z_326989_2
2020-03-04 19:51:01,384 [Controller] [INFO ] Updating All Drivers to ISY for Home - FRONT DOOR(z_326989_2)
2020-03-04 19:51:01,388 [Controller] [DEBUG] Query zone z_326989_3
2020-03-04 19:51:02,056 [Controller] [INFO ] Updating All Drivers to ISY for Home - KITCHEN DOOR(z_326989_3)
2020-03-04 19:51:02,060 [Controller] [DEBUG] Query zone z_326989_4
2020-03-04 19:51:03,281 [Controller] [INFO ] Updating All Drivers to ISY for Home - BASEMENT DOOR(z_326989_4)
2020-03-04 19:51:03,285 [Controller] [DEBUG] Query zone z_326989_5
2020-03-04 19:51:04,002 [Controller] [INFO ] Updating All Drivers to ISY for Home - MAIN MOTION(z_326989_5)
2020-03-04 19:51:04,007 [Controller] [DEBUG] Query zone z_326989_6
2020-03-04 19:51:04,661 [Controller] [INFO ] Updating All Drivers to ISY for Home - BASEMENT MOTION(z_326989_6)
2020-03-04 19:51:04,665 [Controller] [DEBUG] Query zone z_326989_8
2020-03-04 19:51:13,292 [Controller] [INFO ] Updating All Drivers to ISY for Home - (z_326989_8)
2020-03-04 19:51:13,296 [Controller] [DEBUG] Query zone z_326989_12
2020-03-04 19:51:14,262 [Controller] [INFO ] Updating All Drivers to ISY for Home - POLICE PANIC(z_326989_12)

**Comment by dbarentine** [comment]
So the issue isn't the panel but you have automation support in your TC account. I've seen the error before as it was reported by someone else. I thought I had fixed it but maybe it got missed in everything else I was doing.

**Comment by dbarentine** [comment]
This error seems more problematic:
raise IntervalError('Use minutes instead of minute')
schedule.IntervalError: Use minutes instead of minute

What is your refresh_auth_interval value set to?

**Comment by BoomerangThree** [comment]
> refresh_auth_interval = 120
> 

Jeff Mason
…………………………………………………
Facebook  - Jeffrey.Mason
LinkedIn    - JeffreyMMason
FlipBoard  - @BoomerangThree
Twitter       - BoomerangThree

**Comment by dbarentine** [comment]
Thank you. I'll take a look at this as soon as I can. The earliest will be tomorrow night though.

**Comment by dbarentine** [comment]
@BoomerangThree Version 1.3.1 which should be in the nodeserver store shortly should resolve both exceptions in your log message.

If for some reason it isn't let me know and we'll re-open this bug.
